name: "CI"

on:
  push:
    branches:
      - "main"

  pull_request:

permissions:
  contents: read

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Get commit hash
        id: commit
        uses: prompt/actions-commit-hash@v3.0.0

      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov mypy aqt[qt6]

      - name: Test and build add-on
        run: |
          make build

      - name: Create test-results directory
        run: |
          mkdir -p ./test-results
          cp "$GITHUB_EVENT_PATH" ./pytest-junit.xml ./test-results

      - name: Upload test-results artifact
        uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: test-results
          path: test-results

      - name: Upload add-on artifact
        uses: actions/upload-artifact@v4
        with:
          name: answerset-${{ steps.commit.outputs.short }}
          path: answerset.ankiaddon
          if-no-files-found: error
