name: Build Answer Set

on:
  push:
    branches:
    - "main"
  pull_request:
    branches:
    - "main"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    - name: Build add-on
      run: |
        make build

    - name: Upload add-on artifact
      uses: actions/upload-artifact@v3.1.3
      with:
        name: answerset.ankiaddon
        path: answerset.ankiaddon
        if-no-files-found: error
