name: Test Results

on:
  workflow_run:
    workflows:
      - "Build"

    types:
      - completed

permissions:
  actions: read
  checks: write
  pull-requests: write

jobs:
  test-results:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion != 'skipped'

    steps:
      - name: Download and extract test results
        uses: dawidd6/action-download-artifact@246dbf436b23d7c49e21a7ab8204ca9ecd1fe615
        with:
          run_id: ${{ github.event.workflow_run.id }}
          name: test-results
          path: artifacts

      - name: Publish test results
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          commit: ${{ github.event.workflow_run.head_sha }}
          event_file: artifacts/test-results/event.json
          event_name: ${{ github.event.workflow_run.event }}
          files: artifacts/test-results/pytest-junit.xml
